// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAstXxCU40VH3yjDtYyincMKqDz4SnQC6w',
    appId: '1:330364936843:web:297a6e9e400600260fea8e',
    messagingSenderId: '330364936843',
    projectId: 'g-task-sk',
    authDomain: 'g-task-sk.firebaseapp.com',
    storageBucket: 'g-task-sk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk3blOsNffct7xU4hZjcL7h4TrS_HqnAg',
    appId: '1:330364936843:android:4b26bde81e3a8d1c0fea8e',
    messagingSenderId: '330364936843',
    projectId: 'g-task-sk',
    storageBucket: 'g-task-sk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdYyF8WXZLdCOpUJmR0uTSuy0-uVp-HJw',
    appId: '1:330364936843:ios:463aa2307fd152c30fea8e',
    messagingSenderId: '330364936843',
    projectId: 'g-task-sk',
    storageBucket: 'g-task-sk.appspot.com',
    iosBundleId: 'com.sk.gtask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdYyF8WXZLdCOpUJmR0uTSuy0-uVp-HJw',
    appId: '1:330364936843:ios:659d322a50243e7f0fea8e',
    messagingSenderId: '330364936843',
    projectId: 'g-task-sk',
    storageBucket: 'g-task-sk.appspot.com',
    iosBundleId: 'com.sk.gtask.RunnerTests',
  );
}
